export const SAVE_EMPLOYEE_INFO = 'app/App/SAVE_EMPLOYEE_INFO';
export const SAVE_EMPLOYEE_INFO_SUCCESS = 'app/App/SAVE_EMPLOYEE_INFO_SUCCESS';
export const SAVE_EMPLOYEE_INFO_ERROR = 'app/App/SAVE_EMPLOYEE_INFO_ERROR';